"""test

Revision ID: 9b49d2157e3e
Revises: 77933d461f8a
Create Date: 2019-08-11 08:19:26.707154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b49d2157e3e'
down_revision = '77933d461f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('read_times', sa.BigInteger(), nullable=True),
    sa.Column('good', sa.BigInteger(), nullable=True),
    sa.Column('bad', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.Time(), nullable=True),
    sa.Column('update_time', sa.Time(), nullable=True),
    sa.Column('is_delete', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
